function [subjects, muscles_R, muscles_L, functional_labels, analytic_labels, assigned_analytics, base_path] = configureStudyParameters(population_type)
    % Configuration des paramètres de l'étude
    
    % Définition des sujets et chemins selon la population
    switch lower(population_type)
        case 'post_operation'
            subjects = {...
                        'S1', 'S2', 'S3', 'S4', 'S5', ...
                        'S6', 'S7', 'S8', 'S9', 'S10', ...
                        'S11', 'S12', 'S13', 'S14', 'S15', ...
                        'S16', 'S17', 'S18', 'S19', 'S20', ...
                        'S21', 'S22', 'S23', 'S24', 'S25', ...
                        'S26', 'S27', 'S28', 'S29', 'S30', ...
                        'S31', 'S32', 'S33', 'S34', 'S35', ...
                        'S36', 'S37', 'S38', 'S39', 'S40', ...
                        'S41'};
            
            base_path = 'C:\Users\Francalanci Hugo\Documents\MATLAB\Stage Sainte-Justine\HUG\Sujets\Post_operation';
        case 'pre_operation'
            subjects = {...
                        'S1', 'S2', 'S3', 'S4', 'S5', ...
                        'S6', 'S7', 'S8', 'S9', 'S10', ...
                        'S11', 'S12', 'S13', 'S14', 'S15', ...
                        'S16', 'S17', 'S18', 'S19', 'S20', ...
                        'S21', 'S22', 'S23', 'S24', 'S25', ...
                        'S26', 'S27', 'S28', 'S29', 'S30', ...
                        'S31', 'S32', 'S33', 'S34', 'S35', ...
                        'S36', 'S37', 'S38', 'S39', 'S40', ...
                        'S41'};

            base_path = 'C:\Users\Francalanci Hugo\Documents\MATLAB\Stage Sainte-Justine\HUG\Sujets\Pre_operation';
        case 'asymptomatic'
            subjects = {...
                       'A1', 'A2', 'A3', 'A4', 'A5',...
                       'A6', 'A7', 'A8', 'A9', 'A10',...
                       'A11', 'A12', 'A13', 'A14', 'A15',...
                       'A16', 'A17', 'A18', 'A19', 'A20',...
                       'A21', 'A22', 'A23', 'A24', 'A25',...
                       'A26', 'A27', 'A28', 'A29', 'A30',...
                       'A31', 'A32', 'A33', 'A34', 'A35',...
                       'A36', 'A37', 'A38', 'A39', 'A40',...
                       'A41'};
            
            base_path = 'C:\Users\Francalanci Hugo\Documents\MATLAB\Stage Sainte-Justine\HUG\Sujets\Asymptomatic';
        otherwise
            error('Type de population non reconnu: %s', population_type);
    end
    
    % Ajout de la bibliothèque btk  
    addpath(genpath('C:\Users\Francalanci Hugo\Documents\MATLAB\Stage Sainte-Justine\HUG\Toolboxs\btk'));
    
    % Définition des muscles pour les côtés droit et gauche
    muscles_R = {'RDELTA', 'RDELTM', 'RDELTP','RTRAPM', 'RTRAPS', 'RSERRA'};
    muscles_L = {'LDELTA', 'LDELTM', 'LDELTP','LTRAPM', 'LTRAPS', 'LSERRA'};
    
    % Définition des labels pour les tâches
    functional_labels = {
        'Bring hands to the mouth', ...
        'Touch the top of the head', ...
        'Raise hands as high as possible above the head', ...
        'Slide hands as high as possible along the spine'
    };

    analytic_labels = { 
        'Flexion (élévation sagittale)', ...
        'Abduction (élévation coronale)', ...
        'Rotation externe (abduction 0°)', ...
        'Rotation interne (abduction 0°)'
    };
    
    % Assignation sous-tâches analytiques
    assigned_analytics = [1, 2, 2, 2, 2, 2]; % (1 = flexion / 2 = abduction) 
end