function fichier = get_file_path(subject, movement, config)
    % Récupération de la population actuelle
    population = config.current_population;
    
    % Définition du format de nom de fichier selon la population
    if strcmp(population, 'Asymptomatic')
        file_names = {... 
            sprintf('%s-PROTOCOL01-FUNCTIONAL1-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL2-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL3-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL4-01.c3d', subject) ...
        };
    elseif strcmp(population, 'Pre_operatoire')
        file_names = {... 
            sprintf('%s-PROTOCOL01-FUNCTIONAL1-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL2-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL3-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL4-01.c3d', subject) ...
        };
    elseif strcmp(population, 'Post_operatoire')
        file_names = {... 
            sprintf('%s-PROTOCOL01-FUNCTIONAL1-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL2-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL3-01.c3d', subject), ...
            sprintf('%s-PROTOCOL01-FUNCTIONAL4-01.c3d', subject) ...
        };
    else
        error('Population %s non reconnue', population);
    end
    
    % Utilisation du chemin de base spécifique à la population
    chemin_dossier = fullfile(config.populations.(population).base_path, subject);
    fichier = fullfile(chemin_dossier, file_names{movement});
end